service: Zintle
provider:
  name: aws
  runtime: nodejs18.x
  stage: development
  region: ap-south-1
  memorySize: 512
  build:
    esbuild: false # Changed from "false" (string) to false (boolean)
  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
  timeout: 900
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    cors: true

functions:
  app:
    handler: handler.handler
    events:
      - httpApi:
          path: '/{proxy+}'
          method: '*'

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
